<!--
%\VignetteIndexEntry{ahti names}
%\VignetteEngine{knitr::knitr}
%\VignetteEncoding{UTF-8}
-->

Full Names of Species in the `ahti` Data File
=============================================

This table lists full scientific names originally used by Oksanen &
Ahti (1982). The first column (File name) gives the acronym used in
the `ahti` file, and the table is ordered alphabetically by this
acronym. The next columns give the full scientific names used by
Oksanen & Ahti (1982), and the last column popularly accepted current
names.  The current names were searched with the help of **CRAN**
packages **Taxonstand** and **taxize**. The plant names were checked
with **Taxonstand** that uses now frozen Plant List v1.1, and with
**taxize** that uses sources `NCBI` and `iPlant_TNRS`. When these were
in conflict, the alternative was chosen that avoids excessive
splitting into monospecific genera. The lichen names were checked with
**taxize** using Index Fungorum.

File name | Original name | Current name
----------|---------------|-------------
`Antedioi` |	*Antennaria dioica* |
`Arctalpi` |	*Arctostaphylos alpinus* |	*Arctous alpina*
`Arctuvau` |	*Arctostaphylos uva-ursi* |
`Arthcitr` |	*Arthrorhaphis citrinella* |
`Baeoplac` |	*Baeomyces placophyllus* |		
`Baeorose` |	*Baeomyces roseus* |	*Dibaeis baeomyces*
`Baeorufu` |	*Baeomyces rufus* |
`Barblyco` |	*Barbilophozia lycopodioides* |		
`Buxbaphy` |	*Buxbaumia aphylla* |		
`Calaarun` |	*Calamagrostis arundinacea* |		
`Calaepig` |	*Calamagrostis epigejos*		
`Calalapp` |	*Calamagrostis lapponica* |
`Callvulg` |	*Calluna vulgaris* |		
`Careeric` |	*Carex ericetorum* |		
`Cerapurp` |	*Ceratodon purpureus* |		
`Cetrcucu` |	*Cetraria cucullata* |	*Nephromopsis cucullata*	
`Cetreric` |	*Cetraria ericetorum* |		
`Cetrisla` |	*Cetraria islandica* |		
`Cetrniva` |	*Cetraria nivalis* |	*Nephromopsis nivalis*	
`Cladamau` |	*Cladonia amaurocraea* |		
`Cladarbu` |	*Cladina arbuscula* |	*Cladonia arbuscula*	
`Cladbacf` |	*Cladonia bacilliformis* |		
`Cladbaci` |	*Cladonia bacillaris* |	*Cladonia macilenta*
`Cladbell` |	*Cladonia bellidiflora* |		
`Cladbotr` |	*Cladonia botrytes* |		
`Cladcarn` |	*Cladonia carneola* |		
`Cladceno` |    *Cladonia cenotea* |		
`Cladcocc` |	*Cladonia coccifera* |		
`Cladconi` |	*Cladonia coniocraea* |		
`Cladcorn` |	*Cladonia cornuta* |		
`Cladcris` |	*Cladonia crispata* |		
`Cladcyan` |	*Cladonia cyanipes* |		
`Claddefo` |	*Cladonia deformis* coll.|
`Cladfimb` |	*Cladonia fimbriata* |		
`Cladfloe` |	*Cladonia floerkeana* |		
`Cladfurc` |	*Cladonia furcata* |
`Cladgrac` |	*Cladonia gracilis* ssp. *gracilis* |		
`Cladgray` |	*Cladonia grayi* |		
`Cladmacr` |	*Cladonia macrophylla* |		
`Cladmaxi` |	*Cladonia maxima*	|	
`Cladmero` |	*Cladonia merochlorophaea* |		
`Cladmiti` |	*Cladina mitis* | 	*Cladonia mitis*	
`Cladnigr` |	*Cladonia gracilis* ssp. *nigripes* | *Cladonia gracilis* ssp. *elongata*
`Cladphyl` |	*Cladonia phyllophora* |		
`Cladpleu` |	*Cladonia pleurota* |		
`Cladpyxi` |	*Cladonia pyxidata* |		
`Cladrang` |	*Cladina rangiferina* |	*Cladonia rangiferina*	
`Cladsqua` |	*Cladonia squamosa* |		
`Cladstel` |	*Cladina stellaris* |	*Cladonia stellaris*	
`Cladsubf` |	*Cladonia subfurcata* |		
`Cladsubu` |	*Cladonia subulata* |		
`Cladturb` |	*Cladonia gracilis* ssp. *turbinata* |		
`Cladunci` |	*Cladonia uncialis* |		
`Cladvert` |	*Cladonia verticillata* |	*Cladonia cervicornis* ssp. *verticillata*	
`Convmaja` |	*Convallaria majalis* |		
`Descflex` |	*Deschampsia flexuosa* |	*Avenella flexuosa*	
`Dicrdrum` |	*Dicranum drummondii* |		
`Dicrfusc` |    *Dicranum fuscescens* |		
`Dicrmaju` |	*Dicranum majus* |		
`Dicrpoly` |	*Dicranum polysetum* |		
`Dicrscop` |	*Dicranum scoparium* |		
`Dicrspur` |	*Dicranum spurium* |		
`Dicrundu` |	*Dicranum undulatum* |		
`Diphalpi` |	*Diphasium alpinum* |	*Lycopodium alpinum*	
`Diphcomp` |	*Diphasium complanatum* |	*Lycopodium complanatum*	
`Empeherm` |	*Empetrum hermaphroditum* |	*Empetrum nigrum* ssp. *hermaphroditum*	
`Empenigr` |	*Empetrum nigrum* | *Empetrum nigrum* ssp. *nigrum*		
`Epilangu` |	*Epilobium angustifolium* |	*Chamaenerion angustifolium*	
`Festovin` |	*Festuca ovina* |		
`Hepatica` |	Hepaticae (liwerworts) |		
`Hierumbe` |	*Hieracium umbellatum* |	
`Hylosple` |	*Hylocomium splendens* |		
`Hypomacu` |	*Hypochoeris maculata* | *Hypochaeris maculata*	
`Icmaeric` |	*Icmadophila ericetorum* |		
`Lecigran` |	*Lecidea granulosa* |	*Trapeliopsis granulosa*	
`Lecilimo` |	*Lecidea limosa* |	*Protomicarea limosa*	
`Leciulig` |	*Lecidea uliginosa* |	*Placynthiella uliginosa*	
`Ledupalu` |	*Ledum palustre* |	*Rhododendron tomentosum*	
`Linnbore` |	*Linnaea borealis* |
`Luzupilo` |    *Luzula pilosa* |		
`Lycoanno` |	*Lycopodium annotinum* |		
`Melaprat` |	*Melampyrum pratense* |		
`Monohypo` |	*Monotropa hypopitys* |		
`Nepharct` |	*Nephroma arcticum* |		
`Ochrfrig` |	*Ochrolechia frigida* |		
`Ochrgemi` |	*Ochrolechia geminipara* |	*Pertusaria geminipara*	
`Peltapht` |	*Peltigera aphthosa* |		
`Peltleuc` |	*Peltigera leucophlebia* |		
`Peltmala` |	*Peltigera malacea* |		
`Peltpoly` |	*Peltigera polydactyla* |	*Peltigera polydactylon*	
`Peltrufe` |	*Peltigera rufescens* |		
`Peltscab` |	*Peltigera scabrosa* |		
`Phylcoer` |	*Phyllodoce coerulea* |	*Phyllodoce caerulea*	
`Pleuschr` |	*Pleurozium schreberi* |		
`Pohlnuta` |	*Pohlia nutans* |		
`Polycomm` |	*Polytrichum commune* |		
`Polyjuni` |	*Polytrichum juniperinum* |		
`Polyodor` |	*Polygonatum odoratum* |		
`Polypili` |	*Polytrichum piliferum* |		
`Polystri` |	*Polytrichum strictum* |		
`Ptilcili` |	*Ptilidium ciliare* |		
`Ptilcris` |	*Ptilium crista-castrensis* |		
`Ptilpulc` |	*Ptilidium pulcherrimum* |		
`Pycnpapi` |	*Pycnothelia papillaria* |		
`Solivirg` |	*Solidago virgaurea* |		
`Solocroc` |	*Solorina crocea* |		
`Stercond` |	*Stereocaulon condensatum* |		
`Stergran` |	*Stereocaulon grande* |		
`Sterpasc` |	*Stereocaulon paschale* |		
`Stertome` |	*Stereocaulon tomentosum* |		
`Thymserp` |	*Thymus serpyllum* |		
`Tonicumu` |	*Toninia cumulata* |	*Stereocaulon cumulatum*	
`Vaccmyrt` |	*Vaccinium myrtillus* |		
`Vacculig` |	*Vaccinium uliginosum* |		
`Vaccviti` |	*Vaccinium vitis-idaea* |		

### References

Oksanen, J. & Ahti, T. 1982. Lichen-rich pine forest vegetation in
Finland. _Annales Botanici Fennici_ **19,** 275--301.