      SUBROUTINE TOPIND(N,NN,MIND,FEEBLE,Y,INDORD,INDSIG,
     1JJCOL,INDPOT,JNAM,NIND,LIND,PRECIS)
C INPUT IS INDICATOR VALUES STORED IN Y.  SETS UP NIND BEST
C INDICATORS IN INDORD, WITH THEIR SIGN IN INDSIG.  IY IS WORKSPACE.
C NIND IS SET TO MIND UNLESS THERE IS SHORTAGE OF GOOD INDICATORS.
      REAL Y(N)
      INTEGER INDORD(N),INDSIG(MIND),JJCOL(N),INDPOT(NN)
      INTEGER JNAM(NN)
      INTEGER LIND(10)
C---FOLLOWING COMMON BLOCK ADDED BY P.R.MINCHIN SEPT 1986
      COMMON /LUNITS/ IUIN1,IUIN2,IUOUT1,IUOUT2,IUOUT3
      IBIG=10000
      DO 10 J=1,N
   10 INDORD(J)=-IBIG*IFIX(ABS(Y(J)*500.0))-IBIG+J
      CALL ISORT(INDORD,N)
      DO 20 J=1,N
      IV=-INDORD(J)
   20 INDORD(J)=(IV/IBIG)*IBIG-IV+IBIG
C INDORD NOW CONTAINS ORDERING BUT MUST BE DOCTORED TO TRUNCATE OFF
C POOR AND DISALLOWED INDICATORS
      NIND=0
      DO 60 IND=1,N
      IF(NIND.EQ.MIND) GOTO 60
      J=INDORD(IND)
      JJ=JJCOL(J)
      JJP=INDPOT(JJ)
      IF(JJP.LT.1) GOTO 60
      IP=INDPOT(JJP)
      IF(IP.LT.1) GOTO 60
C---Comparison changed to use PRECIS: P.Minchin June 1997
C      IF(ABS(Y(J)).LT.FEEBLE) GOTO 60
      IF(FEEBLE-ABS(Y(J)).GT.PRECIS) GOTO 60
      IL=JNAM(JJ)
      IF(LIND(IL).EQ.0) GOTO 60
      NIND=NIND+1
      INDORD(NIND)=J
      INDPOT(JJP)=-INDPOT(JJP)
      INDSIG(NIND)=1
      IF(Y(J).LT.0) INDSIG(NIND)=-1
   60 CONTINUE
      IF(NIND.EQ.0) GOTO 80
      DO 70 IND=1,NIND
      J=INDORD(IND)
      JJ=JJCOL(J)
      JJP=IABS(INDPOT(JJ))
      INDPOT(JJP)=JJP
   70 CONTINUE
   80 RETURN
      END
C
