      SUBROUTINE UPDATE(M,MM,IC,LEVEL,ICLASS,IIROW,IX)
C UPDATES CLASSIFICATION;  IF DIVISION HAS FAILED, ADDS IEND TO
C CLASS NUMBER IC;  FINDS NEW CLASS IC TO BE DIVIDED.
      INTEGER ICLASS(MM),IIROW(M),IX(M)
C---FOLLOWING COMMON BLOCK ADDED BY P.R.MINCHIN SEPT 1986
      COMMON /LUNITS/ IUIN1,IUIN2,IUOUT1,IUOUT2,IUOUT3
      COMMON/IARBS/ICWEXP,IEND,MMIN,IPREXP,LEVMAX
      COMMON/SWITCH/IFAIL,IDIAGR,ISTOP,IREWT
      IF(IFAIL.EQ.0) GOTO 20
      DO 10 I=1,M
      II=IIROW(I)
   10 ICLASS(II)=ICLASS(II)+IEND
      GOTO 40
C WE NOW APPLY THE DIVISION HELD IN IX(I) (=0 OR 1), AND UPDATE
C THE CLASS REGISTER FOR THE ROWS
   20 DO 30 I=1,M
      II=IIROW(I)
   30 ICLASS(II)=ICLASS(II)*2+IX(I)
C WE NOW FIND THE NEXT CLASS TO BE DIVIDED AND SET ISTOP=1 IF
C WE HAVE COME TO THE END OF THE DIVISIONS
   40 IC=IEND
      DO 50 II=1,MM
      IIC=ICLASS(II)
      IF(IIC.LT.IC)IC=IIC
   50 CONTINUE
      IF(IC.GE.IEND) GOTO 60
      IF(2**LEVEL.GT.IC)GOTO 80
      WRITE (IUOUT2,1000) LEVEL
 1000 FORMAT(/'   END OF LEVEL',I4,//)
      LEVEL=LEVEL+1
      IF (LEVEL.LE.LEVMAX) GOTO 80
   60 ISTOP=1
      WRITE (IUOUT2,1001)
 1001 FORMAT(/'THIS IS THE END OF THE DIVISIONS REQUESTED')
      DO 70 II=1,MM
      IC=ICLASS(II)
      IF(IC.GE.IEND)ICLASS(II)=IC-IEND
   70 CONTINUE
   80 RETURN
      END
C
