      SUBROUTINE PSEUDO(MM,NN,NMAX,NL,NDAT,NSPEC,IDAT,LCUT,
     1JNFLAG,JNAME1,JNAME2,JNAM,INDPOT,IIY)
C SETS UP PSEUDOSPECIES DATA IN IDAT, AND ALSO VECTOR INDPOT,
C WHICH STORES THE REAL SPECIES NUMBERS CORRESPONDING TO THE
C PSEUDOSPECIES.  PSEUDOSPECIES CUT LEVELS ARE IN LCUT.
C SPECIES NAMES IN JNAME1,2.  JNAM STORES LEVELS OF PSEUDOSPECIES.
C---Changed JNAME to CHARACTER: P.Minchin June 1997
      INTEGER JTOP(10),IDAT(NDAT),LCUT(NL),
     1JNFLAG(NMAX),JNAM(NMAX),INDPOT(NMAX),IIY(NMAX)
      INTEGER JNAME1(NMAX),JNAME2(NMAX)
C---FOLLOWING COMMON BLOCK ADDED BY P.R.MINCHIN SEPT 1986
      IBIG=50000
      ID=0
      IDMAX=0
      DO 20 II=1,MM
   15 ID=ID+1
      IDMAX=IDMAX+1
      J=IDAT(ID)
      IF(J.EQ.-1) GOTO 20
      ID=ID+1
      JQ=IDAT(ID)
      JJQ=0
      DO 16 IL=1,NL
      IF(JQ.GE.LCUT(IL))JJQ=JJQ+1
   16 CONTINUE
      IDAT(ID)=JJQ
      IDMAX=IDMAX+JJQ-1
      GOTO 15
   20 CONTINUE
      IF(IDMAX.LE.NDAT) GOTO 40
      IDMAX=IDMAX+50
c      WRITE (IUOUT2,1001) IDMAX
c      WRITE (IUOUT1,1001) IDMAX
c 1001 FORMAT('***ERROR***  DATA ARRAY NEEDS',I6,' ELEMENTS')
      STOP
   40 IID=NDAT
   80 IDAT(IID)=IDAT(ID)
      ID=ID-1
      IID=IID-1
      IF(ID.GT.0) GOTO 80
      DO 90 II=1,MM
      JJJ=0
   84 IID=IID+1
      J=IDAT(IID)
      IF(J.EQ.-1) GOTO 87
      IID=IID+1
      JJQ=IDAT(IID)
      IF(JJQ.EQ.0) GOTO 84
      DO 86 JQ=1,JJQ
      JJJ=JJJ+1
   86 IIY(JJJ)=J+IBIG*(JQ-1)
      GOTO 84
   87 DO 88 JJ=1,JJJ
      ID=ID+1
   88 IDAT(ID)=IIY(JJ)
      ID=ID+1
      IDAT(ID)=-1
      IF(ID.LE.IID) GOTO 90
      IDMAX=IDMAX+300
c      WRITE (IUOUT2,1001) IDMAX
      STOP
   90 CONTINUE
C WE NOW HAVE THE DESIRED INFORMATION IN IDAT.  ALL WE HAVE
C TO DO IS TO CONDENSE THE NUMBERING
      IP=0
      DO 140 IL=1,NL
      DO 100 JJJ=1,NSPEC
  100 IIY(JJJ)=0
      ID=0
      DO 110 II=1,MM
  103 ID=ID+1
      JJJ=IDAT(ID)
      IF(JJJ.EQ.-1) GOTO 110
      IF(JJJ.GE.IBIG) GOTO 103
      IF(JJJ.LT.-1) GOTO 103
      IIY(JJJ)=IIY(JJJ)+1
      GOTO 103
  110 CONTINUE
      DO 120 JJJ=1,NSPEC
      IF(IIY(JJJ).EQ.0) GOTO 120
      IP=IP+1
      IF(IP.LE.NMAX) INDPOT(IP)=JJJ
      IIY(JJJ)=IP
  120 CONTINUE
      ID=0
      DO 130 II=1,MM
  123 ID=ID+1
      JJJ=IDAT(ID)
      IF(JJJ.EQ.-1) GOTO 130
      IF(JJJ.GE.IBIG) GOTO 127
      IF(JJJ.LT.-1) GOTO 123
      JJJ=IIY(JJJ)
  127 IDAT(ID)=JJJ-IBIG
      GOTO 123
  130 CONTINUE
      JTOP(IL)=IP
  140 CONTINUE
      ID=0
      DO 150 II=1,MM
  145 ID=ID+1
      JJ=IDAT(ID)
      IF(JJ.EQ.-1) GOTO 150
      IDAT(ID)=JJ+IBIG
      GOTO 145
  150 CONTINUE
c      WRITE (IUOUT2,1002) ID
c      WRITE (IUOUT1,1002) ID
c 1002 FORMAT(//'LENGTH OF DATA ARRAY AFTER DEFINING PSEUDOSPECIES',
c     1I7)
c      IF(ID*2.GT.NDAT) WRITE (IUOUT2,1003) NDAT
c      IF(ID*2.GT.NDAT) WRITE (IUOUT1,1003) NDAT
c 1003 FORMAT('*** BEWARE ***  THIS EXCEEDS ONE-HALF LENGTH OF',
c     1' DATA ARRAY (=',I6,')'/
c     2'NO SPECIES CLASSIFICATION CAN BE PERFORMED')
      NN=IP
      IF(NN.LE.NMAX) GOTO 155
c      WRITE (IUOUT2,1000) NN
c      WRITE (IUOUT1,1000) NN
c 1000 FORMAT('***ERROR*** - NEEDS DIMENSIONING FOR',I6,
c     1'  PSEUDOSPECIES')
      STOP
  155 NSPEC=JTOP(1)
c      WRITE (IUOUT2,1004) NN
c      WRITE (IUOUT1,1004) NN
c 1004 FORMAT(//'TOTAL NUMBER OF SPECIES AND PSEUDOSPECIES',I7)
c      WRITE (IUOUT2,1005) NSPEC
c      WRITE (IUOUT1,1005) NSPEC
c 1005 FORMAT(//'NUMBER OF SPECIES, EXCLUDING PSEUDOSPECIES ',
c     1'AND ONES WITH NO OCCURRENCES',I5)
      DO 160 JJ=1,NSPEC
      J=INDPOT(JJ)
      IIY(J)=JJ
      JNFLAG(JJ)=JNFLAG(J)
      JNAME1(JJ)=JNAME1(J)
  160 JNAME2(JJ)=JNAME2(J)
      DO 170 JJ=1,NN
      J=INDPOT(JJ)
  170 INDPOT(JJ)=IIY(J)
      JJJ=2
      IL=0
      DO 180 JJ=1,NN
      J=IABS(INDPOT(JJ))
      JNFLAG(JJ)=JNFLAG(J)
      JNAME1(JJ)=JNAME1(J)
      JNAME2(JJ)=JNAME2(J)
      IF(J.LE.JJJ) IL=IL+1
      JNAM(JJ)=IL
  180 JJJ=J
      RETURN
      END
C
