      SUBROUTINE XYMULT(M,MM,N,NN,NDAT,X,Y,IIROW,IADDR,ROWWGT,
     1COLWGT,IDAT)
C FORMS MATRIX PRODUCT Y=AX, APPLYING ROW AND COLUMN WEIGHTS
C ROWWGT,COLWGT.
      REAL X(M),Y(N),ROWWGT(M),COLWGT(N)
      INTEGER IIROW(M),IADDR(MM),IDAT(NDAT)
      DO 10 J=1,N
   10 Y(J)=0.0
      DO 20 I=1,M
      II=IIROW(I)
      AX=X(I)*ROWWGT(I)
      ID=IADDR(II)
   15 J=IDAT(ID)
      IF (J.EQ.-1) GOTO 20
      Y(J)=Y(J)+AX
      ID=ID+1
      GOTO 15
   20 CONTINUE
      DO 30 J=1,N
   30 Y(J)=Y(J)*COLWGT(J)
      RETURN
      END
C
