      SUBROUTINE CLORD(MM,LEVMAX,ICLASS,IX)
C ORDERS SAMPLES IN ORDER OF CLASSIFICATION IN ICLASS, MAKING
C ALLOWANCES FOR DIFFERING LEVELS OF DIVISION
      INTEGER ICLASS(MM),IX(MM)
C---FOLLOWING COMMON BLOCK ADDED BY P.R.MINCHIN SEPT 1986
      COMMON /LUNITS/ IUIN1,IUIN2,IUOUT1,IUOUT2,IUOUT3
      IEND=2**(LEVMAX+2)
      IBIG=10000
      DO 10 II=1,MM
      IC=ICLASS(II)
      IF(IC.EQ.0) GOTO 7
    5 IC=IC*2
      IF(IC.LT.IEND) GOTO 5
      IX(II)=IBIG*IC+II
      GOTO 10
    7 IX(II)=II
   10 CONTINUE
      CALL ISORT(IX,MM)
      DO 12 II=1,MM
      IC=IX(II)
   12 IX(II)=IC-(IC/IBIG)*IBIG
      RETURN
      END
C
