      SUBROUTINE CODESC(M,MM,N,NN,NDAT,NIND,INDORD,IX,IY,
     1IIROW,IADDR,IDAT)
C STARTING WITH NIND BEST INDICATORS, STORES INDICATOR-COMPOSITION
C OF SAMPLES IN CODED FORM IN IX.  THE FIRST (BEST) INDICATOR IS GIVEN
C A CODED SCORE OF 1, THE NEXT A SCORE OF 2, THE NTH A SCORE 2**(N-1).
C CODE NUMBERS ARE ADDED TO OBTAIN CODED INDICATOR-COMPOSITION.
      INTEGER INDORD(N),IX(M),IY(N),IIROW(M),IADDR(MM),IDAT(NDAT)
C---FOLLOWING COMMON BLOCK ADDED BY P.R.MINCHIN SEPT 1986
      COMMON /LUNITS/ IUIN1,IUIN2,IUOUT1,IUOUT2,IUOUT3
      DO 10 J=1,N
   10 IY(J)=0
      IIY=1
      DO 20 IND=1,NIND
      J=INDORD(IND)
      IY(J)=IIY
   20 IIY=IIY*2
      DO 30 I=1,M
      II=IIROW(I)
      IIX=0
      ID=IADDR(II)
   25 J=IDAT(ID)
      IF(J.EQ.-1) GOTO 26
      IIX=IIX+IY(J)
      ID=ID+1
      GOTO 25
   26 IX(I)=IIX
   30 CONTINUE
      RETURN
      END
C
