      SUBROUTINE INDSCO(M,MM,N,NN,NDAT,X,AXPOS,AXNEG,
     1CUT1,CUT2,Y,YY,IIROW,ROWWGT,IADDR,IDAT)
C INPUT IS ORDINATION IN X.  OUTPUT IS NEGATIVE INDICATOR SCORES IN Y,
C POSITIVE INDICATOR SCORES IN YY.  AXPOS,AXNEG ARE ROW-WEIGHTED SUMS
C OF POSITIVE AND NEGATIVE ELEMENTS.  CUT1,CUT2 ARE CUT-POINTS FOR
C     ZONE OF INTERMEDIATENESS.
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IIROW(M),IADDR(MM),IDAT(NDAT)
      REAL(8) X(M),Y(N),YY(N),ROWWGT(M)
      CUTMID=(CUT1+CUT2)/2.0
      CUTHLF=(CUT2-CUT1)/2.0+1.0E-10
      AXPOS=0.0
      AXNEG=0.0
      DO 10 J=1,N
      Y(J)=0.0
   10 YY(J)=0.0
      DO 30 I=1,M
      II=IIROW(I)
      ID=IADDR(II)
      AX=(X(I)-CUTMID)/CUTHLF
      IF(AX.GT.1.0)AX=1.0
      IF(AX.LT.-1.0)AX=-1.0
      IF(AX.GT.0.0) GOTO 26
      AX=AX*ROWWGT(I)
      AXNEG=AXNEG-AX
   25 J=IDAT(ID)
      IF(J.EQ.-1) GOTO 30
      Y(J)=Y(J)-AX
      ID=ID+1
      GOTO 25
   26 AX=AX*ROWWGT(I)
      AXPOS=AXPOS+AX
   27 J=IDAT(ID)
      IF(J.EQ.-1) GOTO 30
      YY(J)=YY(J)+AX
      ID=ID+1
      GOTO 27
   30 CONTINUE
      RETURN
      END
C
