      SUBROUTINE WEIGHT(M,MM,N,NN,NDAT,X,Y,IIROW,IADDR,RRWT,ROWWGT,
     1JJCOL,CCWT,COLWGT,IDAT)
C WEIGHTS COLUMNS ACCORDING TO HOW RARE THEY ARE.  THOSE RARER THAN
C A PROPORTION FRQLIM ARE DOWNWEIGHTED IN PROPORTION TO THEIR
C SHORTFALL FROM FRQLIM, RAISED TO THE POWER ICWEXP.  ROW-WEIGHTS
C FOR SUBMATRIX ARE PUT IN ROWWGT.
      REAL X(M),Y(N),RRWT(MM),ROWWGT(M),CCWT(NN),COLWGT(N)
      INTEGER IIROW(M),IADDR(MM),JJCOL(NN),IDAT(NDAT)
C---Variable PRECIS added P.Minchin  June 1997
      COMMON/LIMS/RARE,FEEBLE,FRQLIM,TOL,RATLIM,REPLIM,PRECIS
      COMMON/IARBS/ICWEXP,IEND,MMIN,IPREXP,LEVMAX
      COMMON/ARBS/CWTMIN,CRLONG,CRCUT
      CWT=1.0-CWTMIN
      IF(FRQLIM.LT.1.0E-10)FRQLIM=1.0E-10
      DO 10 J=1,N
   10 COLWGT(J)=1.0
      TOT=0.0
      DO 20 I=1,M
      II=IIROW(I)
      RR=RRWT(II)
      ROWWGT(I)=RR
      TOT=TOT+RR
   20 X(I)=1.0
      CALL XYMULT(M,MM,N,NN,NDAT,X,Y,IIROW,IADDR,ROWWGT,
     1COLWGT,IDAT)
      DO 30 J=1,N
      JJ=JJCOL(J)
      AY=Y(J)/TOT
      IF(AY.GE.FRQLIM)AY=FRQLIM
      COLWGT(J)=CCWT(JJ)*((AY/FRQLIM)**ICWEXP*CWT+CWTMIN)
   30 CONTINUE
      RETURN
      END
C
