      SUBROUTINE REPORT(M,MM,N,NDAT,IC,X,ROWWGT,
     1     Y,YY,IX,IZONE,IIROW,IY,IADDR,IDAT,ISD2, ISEC)
C     REPORTS ON DICHOTOMY.  TRUE INDICATOR SCORES ARE NOW IN IX.
C     MATRIX IPICT CONTAINS DIAGRAM OF DICHOTOMY, RELATING ZONES
C     TO INDICATOR SCORES.
      IMPLICIT DOUBLEPRECISION (A-H,O-Z)
      REAL(8) X(M),ROWWGT(M),Y(N),YY(N)
C---  Changed ITEM to CHARACTER: P.Minchin June 1997
      INTEGER ITEM(200)
C---  Changed INAME, JNAME to CHARACTER: P.Minchin June 1997
      INTEGER IX(M),IZONE(M),IIROW(M),IY(N),
     1     IADDR(MM),IDAT(NDAT),NCAT(6)
      COMMON/PICT/MZ,MS,IZD,IIZD,ISD,ISHIFT,MZIND,MZCRIT,MZOUT,NIND
C---  Variable PRECIS added P.Minchin  June 1997
      COMMON/LIMS/RARE,FEEBLE,FRQLIM,TOL,RATLIM,REPLIM,PRECIS
      COMMON/SWITCH/IFAIL,IDIAGR,ISTOP,IREWT
      COMMON/IARBS/ICWEXP,IEND,MMIN,IPREXP,LEVMAX
      COMMON/WORK/ITEM
      DO 10 ICAT=1,6
         NCAT(ICAT)=0
 10   CONTINUE
      DO 20 I=1,M
         IZ=IZONE(I)
         IS=IX(I)
         IF(IZ.GT.IIZD) GOTO 13
         IF(IS.GT.ISD) GOTO 12
         ICAT=1
         GOTO 18
 12      ICAT=3
         GOTO 18
 13      IF(IZ.GT.IZD) GOTO 16
         IF(IS.GT.ISD) GOTO 15
         ICAT=2
         GOTO 18
 15      ICAT=5
         GOTO 18
 16      IF(IS.GT.ISD) GOTO 17
         ICAT=6
         GOTO 18
 17      ICAT=4
 18      X(I)=FLOAT(ICAT)
         NCAT(ICAT)=NCAT(ICAT)+1
 20   CONTINUE
      NNEG=NCAT(1)+NCAT(2)+NCAT(3)
      NPOS=NCAT(4)+NCAT(5)+NCAT(6)
      CALL INDSCO(M,MM,N,NDAT,X,AXPOS,AXNEG,3.5,3.5,
     1     Y,YY,IIROW,ROWWGT,IADDR,IDAT)
      PRLIM=(REPLIM-1.0)/(REPLIM+1.0)-0.0001
      DO 30 J=1,N
         AY=Y(J)/AXNEG
         AYY=YY(J)/AXPOS
         IIY=0
C--   Comparisons changed to use PRECIS: P.Minchin June 1997
C     IF(AY.GE.RARE) IIY=1
C     IF(AYY.GE.RARE) IIY=1
         IF((AY-RARE).GE.PRECIS) IIY=1
         IF((AYY-RARE).GE.PRECIS) IIY=1
         PREF=(AYY-AY)/(AYY+AY)
C--   Comparisons changed to use PRECIS: P.Minchin June 1997
C     IF(PREF.GT.PRLIM) GOTO 25
C     IF(PREF.LT.-PRLIM) GOTO 23
         IF((PREF-PRLIM).GT.PRECIS) GOTO 25
         IF((-PREF-PRLIM).GT.PRECIS) GOTO 23
         IY(J)=IIY
         GOTO 30
 23      IY(J)=2*IIY
         GOTO 30
 25      IY(J)=3*IIY
 30   CONTINUE
C     WE NOW HAVE A VARIABLE IY THAT IS 0 FOR RARITIES, 3 FOR POSITIVE
C     PREFERENTIALS, 2 FOR NEGATIVE PREFERENTIALSS, 1 FOR INDIFFERENTS.
      IF(NIND.EQ.0) GOTO 60
      ISD1=ISD-ISHIFT
      ISD2=ISD1+1
 60   IIC=IC*2
      IF(NIND.EQ.0) GOTO 70
      NOUT=NCAT(2)
      IF(NOUT.EQ.0) GOTO 65
 65   NOUT=NCAT(3)
      IF(NOUT.EQ.0) GOTO 70
 70   IIC=IC*2+1
      IF(NIND.EQ.0) GOTO 80
      NOUT=NCAT(5)
      IF(NOUT.EQ.0) GOTO 75
 75   NOUT=NCAT(6)
      IF(NOUT.EQ.0) GOTO 80
C     WE NOW LIST OUT THE COMMONER SPECIES ACCORDING AS THEY ARE
C     PREFERENTIAL OR NEUTRAL
 80   IF(ISEC.EQ.2) GOTO 100
      CALL INDSCO(M,MM,N,NDAT,X,AXPOS,AXNEG,3.5,3.5,
     1     Y,YY,IIROW,ROWWGT,IADDR,IDAT)
 100  RETURN
      END
C
