      SUBROUTINE XMAXMI(X,AXMAX,AXMIN,M)
C CALCULATES MAXIMUM AND MINIMUM OF VECTOR X(M).
      REAL X(M)
C---FOLLOWING COMMON BLOCK ADDED BY P.R.MINCHIN SEPT 1986
      COMMON /LUNITS/ IUIN1,IUIN2,IUOUT1,IUOUT2,IUOUT3
      AXMAX=-1.0E10
      AXMIN=-AXMAX
      DO 10 I=1,M
      AX=X(I)
      IF(AX.GT.AXMAX)AXMAX=AX
      IF(AX.LT.AXMIN)AXMIN=AX
   10 CONTINUE
      RETURN
      END
C
