      SUBROUTINE RECODE(M,MM,N,NN,NDAT,IC,ICLASS,IIROW,
     1     JJCOL,IADDR,IDAT)
C     GIVEN CLASS IC TO BE DIVIDED, CALCULATES M,N, THE NUMBERS OF
C     ROWS AND COLUMNS IN SUBMATRIX DEFINED BY IC.  RENUMBERS THESE
C     WITH CONSECUTIVE NUMBERING, SETTING UP TRANSLATION VECTORS
C     IIROW,JJCOL, TO GET BACK TO OLD NUMBERING WHEN NECESSARY.
      INTEGER ICLASS(MM),IIROW(MM),JJCOL(NN),IADDR(MM),IDAT(NDAT)
      I=0
      DO 10 II=1,MM
         IF (ICLASS(II).NE.IC) GOTO 10
         I=I+1
         IIROW(I)=II
 10   CONTINUE
      M=I
      DO 20 JJ=1,NN
         JJCOL(JJ)=0
 20   CONTINUE
C     NOW ACCUMULATE COLUMN TOTALS IN JJCOL
      DO 30 I=1,M
         II=IIROW(I)
         ID=IADDR(II)
 25      JJ=IDAT(ID)
         IF(JJ.EQ.-1) GOTO 30
         JJCOL(JJ)=JJCOL(JJ)+1
         ID=ID+1
         GOTO 25
 30   CONTINUE
      J=0
      DO 40 JJ=1,NN
         IF(JJCOL(JJ).EQ.0) GOTO 40
         J=J+1
         JJCOL(JJ)=J
 40   CONTINUE
      N=J
C     NOW GO THROUGH THE MATRIX RECODING THE COLUMNS
      DO 50 I=1,M
         II=IIROW(I)
         ID=IADDR(II)
 45      JJ=IDAT(ID)
         IF(JJ.EQ.-1) GOTO 50
         IDAT(ID)=JJCOL(JJ)
         ID=ID+1
         GOTO 45
 50   CONTINUE
C     NOW THE REVERSE CODING J TO JJ IS PUT IN JJCOL
      J=0
      DO 60 JJ=1,NN
         IF(JJCOL(JJ).EQ.0) GOTO 60
         J=J+1
         JJCOL(J)=JJ
 60   CONTINUE
      RETURN
      END
C
