      SUBROUTINE BIN(ITEM,IC)
C CONVERTS CLASS NUMBER IC TO BINARY DIGITS, READY FOR PRINTING OUT
C---ITEM,BLANK,ZERO,ONE,STAR changed to CHARACTER: P.Minchin June 1997
      CHARACTER*4 ITEM(200)
      CHARACTER*1 BLANK,ZERO,ONE,STAR
C---FOLLOWING COMMON BLOCK ADDED BY P.R.MINCHIN SEPT 1986
      COMMON /LUNITS/ IUIN1,IUIN2,IUOUT1,IUOUT2,IUOUT3
      DATA BLANK/' '/,ZERO/'0'/,ONE/'1'/,STAR/'*'/
      LEVEL=0
      IIC=1
   10 IF(IIC.GT.IC) GOTO 20
      IIC=IIC*2
      LEVEL=LEVEL+1
      GOTO 10
   20 DO 30 IT=1,30
   30 ITEM(IT)=BLANK
      IT=LEVEL
      IF(LEVEL.GT.30) IT=30
      IIC=IC
   40 IIIC=IIC/2
      IIC=IIC-2*IIIC
      IF(IIC.EQ.0)ITEM(IT)=ZERO
      IF(IIC.EQ.1)ITEM(IT)=ONE
      IIC=IIIC
      IT=IT-1
      IF(IT.GT.0) GOTO 40
      ITEM(1)=STAR
      RETURN
      END
C
