      SUBROUTINE TABLE(M,MMZ,MMS,MIND,IX,IZONE,INDSIG,IPICT,
     1INDTRU,IIND)
C CODED INDICATOR-COMPOSITION IS IN IX.  CALCULATES MATRIX IPICT,
C RELATING ZONES TO INDICATOR-SCORES.  ONLY IIND TOP INDICATORS ARE
C USED.  ISHIFT IS ADDED TO INDICATOR-SCORES TO KEEP THEM POSITIVE.
C IF THE SWITCH INDTRU=1, SUBROUTINE ALSO REPLACES CODED INDICATOR-
C COMPOSITION BY THE TRUE INDICATOR-SCORES.
      INTEGER IX(M),IZONE(M),INDSIG(MIND),IPICT(MMZ,MMS)
      COMMON/PICT/MZ,MS,IZD,IIZD,ISD,ISHIFT,MZIND,MZCRIT,MZOUT,NIND
      MS=IIND+1
      ISHIFT=1
      DO 10 IND=1,IIND
      IF(INDSIG(IND).LT.0) ISHIFT=ISHIFT+1
   10 CONTINUE
      DO 20 IZ=1,MZ
      DO 21 IS=1,MS
         IPICT(IZ,IS)=0
 21   CONTINUE
 20   CONTINUE
      DO 30 I=1,M
      IZ=IZONE(I)
      IS=ISHIFT
      IIX=IX(I)
      DO 25 IND=1,IIND
      IIIX=IIX/2
      IS=IS+INDSIG(IND)*(IIX-IIIX*2)
      IIX=IIIX
 25   CONTINUE
      IF(INDTRU.EQ.1)IX(I)=IS
      IPICT(IZ,IS)=IPICT(IZ,IS)+1
 30   CONTINUE
      RETURN
      END
C
