      SUBROUTINE DECODE(M,MM,N,NDAT,IIROW,IADDR,IDAT,JJCOL)
C     GOES THROUGH ROWS OF SUBMATRIX, BACKTRANSLATING J TO JJ, I.E.
C     RETURNING TO COLUMN NUMBERING IN FULL MATRIX.
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INTEGER IIROW(M),IADDR(MM),IDAT(NDAT),JJCOL(N)
      DO 10 I=1,M
         II=IIROW(I)
         ID=IADDR(II)
 5       J=IDAT(ID)
         IF(J.EQ.-1) GOTO 10
         IDAT(ID)=JJCOL(J)
         ID=ID+1
         GOTO 5
 10   CONTINUE
      RETURN
      END
C
