      SUBROUTINE CLOSER(YSCORE,IIC,MM,N,NN,NDAT,IEND,TOT0,TOT1,
     1IDAT,ICLASS,IADDR,INDPOT,JJCOL,RRWT,CCWT,Y,Y0,Y1)
C OBTAINS A QUANTITY YSCORE, TO DETERMINE WHICH ORDER THE TWO HALVES
C OF DIVISION SHOULD BE PUT IN.  IF YSCORE IS NEGATIVE, THEN GROUP
C IIC MORE CLOSELY RESEMBLES THE NEGATIVE SIDE OF DIVISION, AND
C VICE VERSA IF YSCORE IS POSITIVE.
      INTEGER IDAT(NDAT),IADDR(MM),ICLASS(MM),INDPOT(NN),JJCOL(NN)
      REAL RRWT(MM),CCWT(NN),Y(NN),Y0(NN),Y1(NN)
      TOT=0.0
      DO 50 JJ=1,NN
   50 Y(JJ)=1.0E-7
      DO 54 II=1,MM
      IIIC=ICLASS(II)
      IF(IIIC.GT.IEND) IIIC=IIIC-IEND
      IF(IIIC.NE.IIC.AND.IIIC/2.NE.IIC.AND.IIIC/4.NE.IIC) GOTO 54
      ID=IADDR(II)
      TOT=TOT+RRWT(II)
   53 JJ=IDAT(ID)
      ID=ID+1
      IF(JJ.EQ.-1) GOTO 54
      JJJ=IABS(INDPOT(JJ))
      Y(JJJ)=Y(JJJ)+RRWT(II)*CCWT(JJ)
      GOTO 53
   54 CONTINUE
      YNEG=0.0
      YIND=0.0
      YPOS=0.0
      X1NEG=0.0
      X1IND=0.0
      X1POS=0.0
      X0NEG=0.0
      X0IND=0.0
      X0POS=0.0
      DO 57 J=1,N
      JJ=JJCOL(J)
      JJJ=IABS(INDPOT(JJ))
      IF(JJ.NE.JJJ) GOTO 57
      AY=Y(JJ)/TOT
      AY0=Y0(JJJ)/TOT0
      AY1=Y1(JJJ)/TOT1
      PREF=ABS(AY0-AY1)/(AY0+AY1)
      PREF=PREF/0.3
      IF(PREF.GT.1.0) PREF=1.0
      PREF=PREF*PREF*PREF*PREF
      IF(AY1.GT.AY0) GOTO 55
      PNEG=PREF
      PIND=(1.0-PREF)
      PPOS=0.0
      GOTO 56
   55 PNEG=0.0
      PIND=(1.0-PREF)
      PPOS=PREF
   56 YNEG=YNEG+PNEG*AY
      YIND=YIND+PIND*AY
      YPOS=YPOS+PPOS*AY
      X0NEG=X0NEG+PNEG*AY0
      X1NEG=X1NEG+PNEG*AY1
      X0IND=X0IND+PIND*AY0
      X1IND=X1IND+PIND*AY1
      X0POS=X0POS+PPOS*AY0
      X1POS=X1POS+PPOS*AY1
   57 CONTINUE
      XNEG=X0NEG+X1NEG
      XIND=X0IND+X1IND
      XPOS=X0POS+X1POS
      IF(XPOS.GT.XNEG)GOTO 58
      IF(XIND.LE.(XNEG-XPOS)) GOTO 59
      YIND=YIND*(XNEG-XPOS)/XIND
      GOTO 59
   58 YIND=-YIND
      XIND=-XIND
      IF(-XIND.LE.(XPOS-XNEG)) GOTO 59
      YIND=YIND*(XPOS-XNEG)/(-XIND)
   59 YSCORE=YPOS-YNEG+YIND
      YSCORE=YSCORE*TOT
      RETURN
      END
C
