      SUBROUTINE ZONEUP(X,AXMIN,CRMIN,CRMAX,AXMAX,M,MZ,MZOUT,
     1MZCRIT,IZONE)
C INPUT IS ORDINATION IN VECTOR X, WITH MAXIMUM AXMAX, MINIMUM
C AXMIN.  SETS UP ZONED ORDINATION, STORED IN VECTOR IZONE.
C CRITICAL ZONE LIES BERTWEEN CRMIN,CRMAX.  TOTAL NUMBER OF
C ZONES IS MZ.
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      REAL(8) X(M)
      INTEGER IZONE(M)
      MZCRIT=MZ-2*MZOUT
      SMALL=1.0E-10
      SEG1=(CRMIN-AXMIN)/(FLOAT(MZOUT)+SMALL)+SMALL
      SEG2=(CRMAX-CRMIN)/(FLOAT(MZCRIT)+SMALL)+SMALL
      SEG3=(AXMAX-CRMAX)/(FLOAT(MZOUT)+SMALL)+SMALL
      DO 10 I=1,M
      AX=X(I)
      IF(AX.GE.CRMIN) GOTO 3
      IZ=IDINT((AX-AXMIN)/SEG1)+1
      IF(IZ.GT.MZOUT) IZ=MZOUT
      IF(IZ.LT.1)IZ=1
      GOTO 8
    3 IF(AX.LE.CRMAX) GOTO 6
      IZ=IDINT((AX-CRMAX)/SEG3)+1
      IF(IZ.LT.1) IZ=1
      IF(IZ.GT.MZOUT) IZ=MZOUT
      IZ=IZ+MZ-MZOUT
      GOTO 8
    6 IZ=IDINT((AX-CRMIN)/SEG2)+1
      IF(IZ.LT.1)IZ=1
      IF(IZ.GT.MZCRIT)IZ=MZCRIT
      IZ=IZ+MZOUT
    8 IZONE(I)=IZ
   10 CONTINUE
      RETURN
      END
C
C---Argument PRECIS added by P.Minchin June 1997
